version: '3.6'

services:
  database:
      image: postgres
      ports:
        - 5432:5432
      networks:
        - default
        - nexus
      environment:
        - POSTGRES_USER=${POSTGRES_USER:-nexus}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nexus}
        - POSTGRES_DB=${POSTGRES_DB:-nexus}
  nexus:
    image: ${DOCKER_IMAGE_NAME:-ilha/nexus}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${ENGINE_PORT:-8000}:8000
    networks:
      - default
      - nexus
    environment:
      - SECRET_KEY=${SECRET_KEY:-SK}
      - DEBUG=${DEBUG:-true}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DEFAULT_DATABASE=${DEFAULT_DATABASE:-postgres://nexus:nexus@database:5432/nexus}
  redis:
    image: redis
    ports:
      - 6379:6379
networks:
  nexus:
    external: true