version: '3.6'

services:
  database:
      image: postgres
      ports:
        - 5432:5432
      networks:
        - default
        - nexus
      environment:
        - POSTGRES_USER=${POSTGRES_USER:-nexus}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nexus}
        - POSTGRES_DB=${POSTGRES_DB:-nexus}
  nexus:
    image: ${DOCKER_IMAGE_NAME:-ilha/nexus}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${ENGINE_PORT:-80}:80
    networks:
      - default
      - nexus
    environment:
      - SECRET_KEY=${SECRET_KEY:-SK}
      - DEBUG=${DEBUG:-true}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DEFAULT_DATABASE=${DEFAULT_DATABASE:-postgres://nexus:nexus@database:5432/nexus}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nexus
      - redis
      - database
    networks:
      - default
      - nexus
    command: celery -A nexus worker -l info -B
    environment:
       - SECRET_KEY=${SECRET_KEY:-SK}
        - DEBUG=${DEBUG:-true}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
        - DEFAULT_DATABASE=${DEFAULT_DATABASE:-postgres://nexus:nexus@database:5432/nexus}
        - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
  redis:
    image: redis
    ports:
      - 6379:6379

networks:
  nexus:
    external: true