# Generated by Django 4.2.8 on 2024-02-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='template_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_type', to='projects.templatetype'),
        ),
    ]
