# Generated by Django 4.2.10 on 2024-04-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="brain_on",
            field=models.BooleanField(default=False),
        ),
    ]
