# Generated by Django 4.2.10 on 2024-07-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVersion',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setup', models.JSONField(default=dict)),
            ],
        ),
    ]
