# Generated by Django 4.2.10 on 2024-08-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_uuid', models.UUIDField()),
                ('current_version_setup', models.JSONField(default=dict)),
                ('is_integrated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrated_features', to='projects.project')),
            ],
        ),
    ]
