# Generated by Django 4.2.10 on 2024-08-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        ('projects', '0006_featureversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedFeatureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actions', models.ManyToManyField(to='actions.flow')),
                ('feature_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.featureversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
