# Generated by Django 4.2.10 on 2024-09-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_integratedfeature'),
        ('projects', '0006_project_indexer_database'),
    ]

    operations = [
    ]
