# Generated by Django 4.2.10 on 2024-10-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_integratedfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integratedfeature',
            name='current_version_setup',
            field=models.JSONField(default=list),
        ),
    ]
