# Generated by Django 4.2.10 on 2024-09-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20240918_1316'),
        ('projects', '0007_merge_20240918_1539'),
    ]

    operations = [
    ]
