# Generated by Django 4.2.10 on 2024-09-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20240918_1539'),
        ('projects', '0007_merge_20240930_1911'),
    ]

    operations = [
    ]
