# Generated by Django 4.2.10 on 2024-10-10 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_integratedfeature_current_version_setup"),
        ("projects", "0007_project_indexer_database"),
    ]

    operations = []
