# Generated by Django 4.2.10 on 2025-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_merge_20241010_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='agents_backend',
            field=models.CharField(choices=[('BedrockBackend', 'BedrockBackend')], default='BedrockBackend', max_length=100),
        ),
    ]
