# Generated by Django 4.2.10 on 2025-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_agents_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='agents_backend',
            field=models.CharField(default='BedrockBackend', max_length=100),
        ),
    ]
