# Generated by Django 4.2.10 on 2025-04-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_inline_agent_switch_project_rationale_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_components',
            field=models.BooleanField(default=False),
        ),
    ]
