# Generated by Django 4.2.10 on 2025-07-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_default_supervisor_foundation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conversation_turns_to_include',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='project',
            name='exclude_previous_thinking_steps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='use_prompt_creation_configurations',
            field=models.BooleanField(default=False),
        ),
    ]
