# Generated by Django 4.2.10 on 2025-08-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0007_alter_openaisupervisor_options_and_more'),
        ('projects', '0016_alter_project_use_prompt_creation_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guardrail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrail', to='inline_agents.guardrail'),
        ),
    ]
