# Generated by Django 4.2.10 on 2025-08-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0008_alter_openaisupervisor_options'),
        ('projects', '0017_project_guardrail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guardrail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='inline_agents.guardrail'),
        ),
    ]
