# Generated by Django 4.2.10 on 2025-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_guardrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_collaborators_foundation_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
