# Generated by Django 4.2.10 on 2025-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_project_default_collaborators_foundation_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="agents_backend",
            field=models.CharField(default="OpenAIBackend", max_length=100),
        ),
    ]
