# Generated by Django 4.2.10 on 2025-11-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_agents_backend'),
        ('projects', '0021_project_formatter_instructions_and_more'),
    ]

    operations = [
    ]
