# Generated by Django 4.2.10 on 2025-12-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='audio_orchestration_welcome_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='formatter_tools_descriptions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
