# Generated by Django 4.2.27 on 2026-01-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0020_supervisoragent'),
        ('projects', '0024_project_audio_orchestration_welcome_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisor_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inline_agents.supervisoragent'),
        ),
    ]
