# Generated by Django 4.2.27 on 2026-03-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_manager_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(max_length=64)),
                ('is_default_for_preview', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='projects.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_for_preview', True)), fields=('project',), name='projects_channel_unique_default_per_project'),
        ),
    ]
