# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="inline_agent_switch",
            field=models.BooleanField(default=True),
        ),
    ]
