# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_alter_project_inline_agent_switch_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bedrock_ingestion_strategy",
            field=models.CharField(
                choices=[("JOB", "Job"), ("DIRECT", "Direct")],
                default="JOB",
                max_length=10,
            ),
        ),
    ]
