# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_project_bedrock_ingestion_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="knowledge_base_version",
            field=models.CharField(default="1", max_length=32),
        ),
    ]
