# Generated by Django 4.2.29 on 2026-07-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_knowledge_base_version'),
        ('projects', '0030_projectairesolutioncriterion'),
    ]

    operations = [
    ]
