# Generated by Django 4.2.27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0030_projectguardrailsconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedrockGuardrailPool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("combination_key", models.CharField(db_index=True, max_length=512, unique=True)),
                ("category_slugs", models.JSONField(default=list)),
                ("bedrock_guardrail_identifier", models.CharField(max_length=255)),
                ("bedrock_guardrail_version", models.CharField(max_length=64)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bedrock Guardrail pool",
                "verbose_name_plural": "Bedrock Guardrail pools",
            },
        ),
        migrations.AddField(
            model_name="projectguardrailsconfig",
            name="bedrock_guardrail_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectguardrailsconfig",
            name="bedrock_guardrail_version",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="projectguardrailsconfig",
            name="bedrock_guardrail_pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_configs",
                to="projects.bedrockguardrailpool",
            ),
        ),
    ]
