# Generated by Django 4.2.27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0031_merge_20260713_2054"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGuardrailsConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_states", models.JSONField(default=dict)),
                ("blocking_message", models.TextField(blank=True, null=True)),
                ("initialized_as_new_project", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardrails_config",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
