# Generated by Django 4.2.29 on 2026-08-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_project_rationale_switch_default'),
        ('projects', '0036_project_is_live_desk_copilot'),
        ('projects', '0036_project_vtex_account_vtex_host_store_storefront_type'),
    ]

    operations = [
    ]
