# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_alter_project_indexer_database_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="rationale_switch",
            field=models.BooleanField(default=True),
        ),
    ]
