# Generated by Django 4.2.10 on 2024-04-02 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intelligences', '0013_alter_contentbaselogs_wenigpt_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('fallback', models.BooleanField(default=False)),
                ('content_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='intelligences.contentbase')),
            ],
        ),
    ]
