# Generated by Django 4.2.10 on 2024-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='product_handler',
            field=models.BooleanField(default=False),
        ),
    ]
