# Generated by Django 4.2.10 on 2024-08-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='action_usage',
            field=models.IntegerField(default=0),
        ),
    ]
