# Generated by Django 4.2.10 on 2024-09-04 18:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='action_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('whatsapp_cart', 'WhatsApp Cart'), ('localization', 'Localization'), ('attachment', 'Attachment')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='flow',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(condition=models.Q(('action_type', 'custom'), _negated=True), fields=('action_type', 'action_type'), name='unique_action_type_except_custom_per_content_base'),
        ),
        migrations.AddField(
            model_name='flow',
            name='action_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='actions.templateaction'),
        ),
    ]
