# Generated by Django 4.2.10 on 2024-09-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_flow_group_templateaction_display_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='action_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='actions.templateaction'),
        ),
    ]
