# Generated by Django 4.2.10 on 2024-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_flow_action_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='action_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('whatsapp_cart', 'WhatsApp Cart'), ('localization', 'Localization'), ('attachment', 'Attachment'), ('safe_guard', 'Safe Guard')], default='custom', max_length=50),
        ),
    ]
