# Generated by Django 4.2.10 on 2024-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0006_alter_flow_action_type_alter_flow_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
