# Generated by Django 4.2.10 on 2024-10-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0007_flow_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="flow_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
