# Generated by Django 4.2.10 on 2024-10-18 15:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0010_auto_20241018_1409"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
