# Generated by Django 4.2.10 on 2024-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0011_alter_flow_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="send_to_llm",
            field=models.BooleanField(default=False),
        ),
    ]
