# Generated by Django 4.2.8 on 2023-12-22 17:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intelligences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskManager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[("loading", "Loading"), ("success", "Success"), ("fail", "Fail"), ("waiting", "Wait")],
                        default="waiting",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentBaseFileTaskManager",
            fields=[
                (
                    "taskmanager_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="task_managers.taskmanager",
                    ),
                ),
                (
                    "content_base_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_tasks",
                        to="intelligences.contentbasefile",
                    ),
                ),
            ],
            bases=("task_managers.taskmanager",),
        ),
    ]
