# Generated by Django 4.2.8 on 2024-01-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0002_contentbasefile_file_name'),
        ('task_managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBaseTextTaskManager',
            fields=[
                ('taskmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_managers.taskmanager')),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('content_base_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_tasks', to='intelligences.contentbasetext')),
            ],
            bases=('task_managers.taskmanager',),
        ),
    ]
