# Generated by Django 4.2.10 on 2024-03-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0010_alter_contentbaselogs_wenigpt_version"),
        ("task_managers", "0002_contentbasetexttaskmanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBaseLinkTaskManager",
            fields=[
                (
                    "taskmanager_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="task_managers.taskmanager",
                    ),
                ),
                (
                    "content_base_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_tasks",
                        to="intelligences.contentbaselink",
                    ),
                ),
            ],
            bases=("task_managers.taskmanager",),
        ),
    ]
