# Generated by Django 4.2.10 on 2025-01-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_activeagent_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
