# Generated by Django 4.2.10 on 2025-01-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeagent',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_agents', to='agents.team'),
        ),
        migrations.AlterUniqueTogether(
            name='activeagent',
            unique_together={('agent', 'team')},
        ),
    ]
