# Generated by Django 4.2.10 on 2025-02-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_merge_20241010_2217"),
        ("agents", "0005_alter_activeagent_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("placeholder", models.CharField(max_length=255, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
                ("agents", models.ManyToManyField(to="agents.agent")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credentials", to="projects.project"
                    ),
                ),
            ],
        ),
    ]
