# Generated by Django 4.2.10 on 2025-02-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="key",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
