# Generated by Django 4.2.10 on 2025-02-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_credential_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="value",
            field=models.CharField(max_length=8192),
        ),
    ]
