# Generated by Django 4.2.10 on 2025-02-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_credential_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_agents', to='agents.agent'),
        ),
    ]
