# Generated by Django 4.2.10 on 2025-03-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_merge_20241010_2217'),
        ('agents', '0009_alter_activeagent_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_fields', to='agents.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_fields', to='projects.project')),
            ],
        ),
    ]
