# Generated by Django 4.2.10 on 2025-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_activeagent_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='type',
            field=models.CharField(choices=[('VTEX_APP', 'VTEX App'), ('PLATFORM', 'Platform')], default='PLATFORM', max_length=255),
        ),
    ]
