# Generated by Django 4.2.10 on 2025-03-20 13:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_merge_20241010_2217"),
        ("agents", "0010_contactfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("user_text", models.TextField()),
                ("agent_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contact_urn", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("source", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_messages",
                        to="projects.project",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agent_messages", to="agents.team"
                    ),
                ),
            ],
        ),
    ]
