# Generated by Django 4.2.10 on 2025-03-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_source_type'),
        ('agents', '0011_team_human_support_team_human_support_prompt'),
    ]

    operations = [
    ]
