# Generated by Django 4.2.10 on 2025-03-27 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_agentmessage"),
        ("agents", "0011_team_human_support_team_human_support_prompt"),
    ]

    operations = []
