TRACES_FILES_SCHEMA_VERSION = "1.0"
DEFAULT_PRESIGNED_URL_EXPIRATION_SECONDS = 86_400

INLINE_TRACES_PREFIX = "inline_traces"
LEGACY_TRACES_PREFIX = "traces"

TRACE_TYPE_INLINE = "inline"
TRACE_TYPE_LEGACY = "legacy"
