# Generated by Django 4.2.10 on 2025-04-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inline_agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("instruction", models.TextField()),
                ("foundation_model", models.CharField(max_length=255)),
                ("prompt_override_configuration", models.JSONField()),
                ("action_groups", models.JSONField()),
                ("knowledge_bases", models.JSONField()),
                ("human_support_prompt", models.TextField(blank=True, null=True)),
                ("human_support_action_groups", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
