# Generated by Django 4.2.10 on 2025-04-16 12:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_project_inline_agent_switch_project_rationale_switch"),
        ("inline_agents", "0002_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="source_type",
            field=models.CharField(
                choices=[("VTEX_APP", "VTEX App"), ("PLATFORM", "Platform")], default="PLATFORM", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="InlineAgentMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("text", models.TextField()),
                ("session_id", models.CharField(max_length=255)),
                ("contact_urn", models.CharField(max_length=255)),
                ("source_type", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_agent_messages",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255)),
                ("value_type", models.CharField(max_length=255)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_contact_fields",
                        to="inline_agents.agent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_contact_fields",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, null=True)),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(default="", max_length=8192)),
                ("placeholder", models.CharField(max_length=255, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("metadata", models.JSONField(default=dict)),
                ("agents", models.ManyToManyField(to="inline_agents.agent")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_credentials",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
