# Generated by Django 4.2.10 on 2025-04-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_inline_agent_switch_project_rationale_switch'),
        ('inline_agents', '0002_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_contact_fields', to='inline_agents.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_contact_fields', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(max_length=255)),
                ('is_confidential', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_credentials', to='inline_agents.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_credentials', to='projects.project')),
            ],
        ),
    ]
