# Generated by Django 4.2.10 on 2025-04-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0003_agent_source_type_inlineagentmessage_contactfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='components_human_support_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='components_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
