# Generated by Django 4.2.10 on 2025-05-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_use_components'),
        ('inline_agents', '0004_supervisor_components_human_support_prompt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentcredential',
            unique_together={('project', 'key')},
        ),
    ]
