# Generated by Django 4.2.10 on 2025-07-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0006_alter_supervisor_instruction'),
        ('inline_agents', '0006_openaisupervisor'),
    ]

    operations = [
    ]
