# Generated by Django 4.2.10 on 2025-08-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0006_alter_supervisor_instruction_and_more'),
        ('inline_agents', '0006_openaisupervisor'),
    ]

    operations = [
    ]
