# Generated by Django 4.2.10 on 2025-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0006_openaisupervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaisupervisor',
            options={'verbose_name': 'OpenAI Supervisor', 'verbose_name_plural': 'OpenAI Supervisors'},
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='instruction',
            field=models.TextField(verbose_name='Default prompt'),
        ),
    ]
