# Generated by Django 4.2.10 on 2025-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0006_openaisupervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaisupervisor',
            options={'verbose_name': 'OpenAI Supervisor', 'verbose_name_plural': 'OpenAI Supervisors'},
        ),
        migrations.AddField(
            model_name='agent',
            name='foundation_models',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
