# Generated by Django 4.2.10 on 2025-08-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0007_alter_openaisupervisor_options_and_more'),
        ('inline_agents', '0007_merge_20250808_1132'),
    ]

    operations = [
    ]
