# Generated by Django 4.2.10 on 2025-08-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_guardrail'),
        ('inline_agents', '0008_alter_openaisupervisor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineAgentsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agents_backend', models.CharField(max_length=100)),
                ('default_instructions_for_collaborators', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_agent_configurations', to='projects.project')),
            ],
            options={
                'verbose_name': 'Inline agents configurations for a project',
                'verbose_name_plural': 'Inline agents configurations for a project',
            },
        ),
    ]
