# Generated by Django 4.2.10 on 2025-09-02 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_alter_project_guardrail"),
        ("inline_agents", "0009_inlineagentsconfiguration"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inlineagentsconfiguration",
            unique_together={("project", "agents_backend")},
        ),
    ]
