# Generated by Django 4.2.10 on 2025-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0011_openaisupervisor_default_instructions_for_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='foundation_models',
            field=models.JSONField(default=dict),
        ),
    ]
