# Generated by Django 4.2.10 on 2025-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0011_openaisupervisor_default_instructions_for_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='foundation_models',
            field=models.JSONField(default={'BedrockBackend': 'us.anthropic.claude-3-5-sonnet-20241022-v2:0', 'OpenAIBackend': 'gpt-5-mini'}),
        ),
    ]
