# Generated by Django 4.2.10 on 2025-09-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0013_openaisupervisor_max_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='foundation_model',
        ),
    ]
