# Generated by Django 4.2.10 on 2025-10-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0013_openaisupervisor_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaisupervisor',
            name='components_instructions_up_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Components Instructions UP'),
        ),
        migrations.AlterField(
            model_name='openaisupervisor',
            name='components_human_support_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Formatter agent instructions'),
        ),
    ]
