# Generated by Django 4.2.10 on 2025-10-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0014_openaisupervisor_components_instructions_up_prompt_and_more'),
        ('inline_agents', '0014_remove_agent_foundation_model'),
    ]

    operations = [
    ]
