# Generated by Django 4.2.10 on 2025-11-12 12:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0015_make_foundation_model_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='audio_orchestration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='text_orchestration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inlineagentsconfiguration',
            name='audio_orchestration_exclusive_tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='inlineagentsconfiguration',
            name='text_orchestration_exclusive_tools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
