# Generated by Django 4.2.10 on 2025-11-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0015_merge_20251014_1900'),
        ('inline_agents', '0016_openaisupervisor_exclude_tools_from_audio_orchestration_and_more'),
    ]

    operations = [
    ]
