# Generated by Django 4.2.10 on 2025-11-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0017_inlineagentsconfiguration_audio_orchestration_and_more'),
        ('inline_agents', '0017_merge_20251112_1544'),
    ]

    operations = [
    ]
