# Generated by Django 4.2.10 on 2025-12-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0017_inlineagentsconfiguration_audio_orchestration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaisupervisor',
            name='audio_orchestration_max_tokens',
            field=models.IntegerField(blank=True, default=2048, help_text='Maximum number of tokens to generate for audio orchestration', null=True),
        ),
        migrations.AddField(
            model_name='openaisupervisor',
            name='audio_orchestration_max_tokens_collaborator',
            field=models.IntegerField(blank=True, default=2048, help_text='Maximum number of tokens to generate for audio orchestration for collaborators', null=True),
        ),
        migrations.AddField(
            model_name='openaisupervisor',
            name='max_tokens_collaborator',
            field=models.IntegerField(blank=True, default=2048, help_text='Maximum number of tokens to generate', null=True),
        ),
    ]
