# Generated by Django 4.2.10 on 2026-01-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0018_openaisupervisor_audio_orchestration_max_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('shared_config', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AgentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='catalog',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='policies',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tooling',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='integratedagent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='MCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='mcps', to='inline_agents.agent')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcps', to='inline_agents.agentsystem')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('agent', 'system', 'name')},
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='inline_agents.agenttype'),
        ),
        migrations.AddField(
            model_name='agent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='inline_agents.agentcategory'),
        ),
        migrations.AddField(
            model_name='agent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='inline_agents.agentgroup'),
        ),
        migrations.AddField(
            model_name='agent',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='agents', to='inline_agents.agentsystem'),
        ),
        migrations.CreateModel(
            name='MCPCredentialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Credential key (e.g., BASE_URL)', max_length=255)),
                ('label', models.CharField(help_text='Display label', max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('is_confidential', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_templates', to='inline_agents.mcp')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('mcp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MCPConfigOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name (e.g., REGIONALIZATION)', max_length=255)),
                ('label', models.CharField(help_text='Display label', max_length=255)),
                ('type', models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('SELECT', 'Select'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('SWITCH', 'Switch'), ('RADIO', 'Radio')], default='SELECT', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text="For SELECT/RADIO type: [{'name': 'Display', 'value': 'internal'}]")),
                ('default_value', models.JSONField(blank=True, default=None, help_text='Default value. Type depends on field type (str, int, bool, etc.)', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('mcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_options', to='inline_agents.mcp')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('mcp', 'name')},
            },
        ),
    ]
