# Generated by Django 4.2.10 on 2025-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0019_agentcategory_agentgroup_agentsystem_agenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='catalog',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='policies',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='tooling',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
