# Generated by Django 4.2.27 on 2026-01-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0020_supervisoragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisoragent',
            name='base_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='default_instructions_for_collaborators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='footer_components_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='formatter_agent_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='header_components_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='human_support_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='human_support_tools',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='knowledge_bases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisoragent',
            name='tools',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
