# Generated by Django 4.2.10 on 2026-01-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0020_supervisoragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='constants',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
