# Generated by Django 4.2.10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0020_agent_capabilities_agent_catalog_agent_policies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedagent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(limit_choices_to={'is_official': True}, on_delete=django.db.models.deletion.CASCADE, related_name='mcps', to='inline_agents.agent')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcps', to='inline_agents.agentsystem')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('agent', 'system', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MCPConfigOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name (e.g., REGIONALIZATION)', max_length=255)),
                ('label', models.CharField(help_text='Display label', max_length=255)),
                ('type', models.CharField(choices=[('CHECKBOX', 'Checkbox'), ('SELECT', 'Select'), ('TEXT', 'Text'), ('NUMBER', 'Number')], default='SELECT', max_length=20)),
                ('options', models.JSONField(default=list, help_text="For SELECT type: [{'name': 'Display', 'value': 'internal'}]")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('mcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_options', to='inline_agents.mcp')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('mcp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MCPCredentialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Credential key (e.g., BASE_URL)', max_length=255)),
                ('label', models.CharField(help_text='Display label', max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('is_confidential', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_templates', to='inline_agents.mcp')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('mcp', 'name')},
            },
        ),
    ]

