# Generated by Django 4.2.10 on 2026-01-13 13:15

from django.db import migrations, models


def clear_agent_associations(apps, schema_editor):
    MCP = apps.get_model('inline_agents', 'MCP')
    MCP.objects.all().update(agent=None)


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0020_manageragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='constants',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='agentsystem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mcp',
            name='agent',
            field=models.ForeignKey(
                limit_choices_to={'is_official': True},
                null=True,
                blank=True,
                on_delete=models.CASCADE,
                related_name='mcps',
                to='inline_agents.agent'
            ),
        ),
        migrations.RunPython(
            clear_agent_associations,
            reverse_migrate,
        ),
        migrations.AddField(
            model_name='agent',
            name='mcps',
            field=models.ManyToManyField(blank=True, related_name='agents', to='inline_agents.mcp'),
        ),
        migrations.AlterUniqueTogether(
            name='mcp',
            unique_together={('system', 'name')},
        ),
        migrations.RemoveField(
            model_name='mcp',
            name='agent',
        ),
        migrations.AddField(
            model_name='agentsystem',
            name='logo',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='agent_systems/logos/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])],
            ),
        ),
        migrations.CreateModel(
            name='AgentGroupModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_example', models.JSONField(blank=True, default=list)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modal', to='inline_agents.agentgroup')),
            ],
        ),
    ]
