# Generated by Django 4.2.10 on 2026-01-24 15:30

from django.db import migrations, models
from django.utils.text import slugify


def populate_mcp_slugs(apps, schema_editor):
    MCP = apps.get_model("inline_agents", "MCP")
    for mcp in MCP.objects.all():
        if not mcp.slug:
            system_name = mcp.system.name if mcp.system else "no_system"
            base_slug = slugify(f"{system_name} {mcp.name}")
            slug = base_slug
            counter = 1
            while MCP.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            mcp.slug = slug
            mcp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0021_add_constants_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcp',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_mcp_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mcp',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='agentgroup',
            name='mcps',
            field=models.ManyToManyField(blank=True, related_name='groups', to='inline_agents.mcp'),
        ),
    ]
