# Generated by Django 4.2.10 on 2026-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0021_add_constants_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcp',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agentgroup',
            name='mcps',
            field=models.ManyToManyField(blank=True, related_name='groups', to='inline_agents.mcp'),
        ),
    ]
