# Generated by Django 4.2.10 on 2026-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0021_add_constants_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsystem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
