# Generated by Django 4.2.10 on 2026-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0022_make_agentsystem_metadata_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mcp',
            unique_together={('system', 'name')},
        ),
        migrations.AddField(
            model_name='agent',
            name='mcps',
            field=models.ManyToManyField(blank=True, related_name='agents', to='inline_agents.mcp'),
        ),
        migrations.RemoveField(
            model_name='mcp',
            name='agent',
        ),
    ]
