# Generated by Django 4.2.10 on 2026-01-19 20:22

from django.db import migrations, models


def clear_agent_associations(apps, schema_editor):
    MCP = apps.get_model('inline_agents', 'MCP')
    MCP.objects.all().update(agent=None)


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0022_make_agentsystem_metadata_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcp',
            name='agent',
            field=models.ForeignKey(
                limit_choices_to={'is_official': True},
                null=True,
                blank=True,
                on_delete=models.CASCADE,
                related_name='mcps',
                to='inline_agents.agent'
            ),
        ),
        migrations.RunPython(
            clear_agent_associations,
            reverse_migrate,
        ),
        migrations.AddField(
            model_name='agent',
            name='mcps',
            field=models.ManyToManyField(blank=True, related_name='agents', to='inline_agents.mcp'),
        ),
        migrations.AlterUniqueTogether(
            name='mcp',
            unique_together={('system', 'name')},
        ),
        migrations.RemoveField(
            model_name='mcp',
            name='agent',
        ),
    ]
