# Generated by Django 4.2.10 on 2026-01-19 17:54

from django.db import migrations, models
from django.db.models import Count


def consolidate_duplicate_mcps_and_migrate_relationships(apps, schema_editor):
    MCP = apps.get_model('inline_agents', 'MCP')
    Agent = apps.get_model('inline_agents', 'Agent')
    MCPConfigOption = apps.get_model('inline_agents', 'MCPConfigOption')
    MCPCredentialTemplate = apps.get_model('inline_agents', 'MCPCredentialTemplate')
    
    duplicates = (
        MCP.objects.values('system_id', 'name')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    for dup in duplicates:
        system_id = dup['system_id']
        name = dup['name']
        
        duplicate_mcps = MCP.objects.filter(system_id=system_id, name=name).order_by('id')
        keep_mcp = duplicate_mcps.first()
        remove_mcps = list(duplicate_mcps[1:])
        
        agents_to_associate = set()
        for mcp in duplicate_mcps:
            if mcp.agent_id:
                agents_to_associate.add(mcp.agent_id)
        
        for agent_id in agents_to_associate:
            agent = Agent.objects.get(pk=agent_id)
            agent.mcps.add(keep_mcp)
        
        for mcp_to_remove in remove_mcps:
            for config_option in mcp_to_remove.config_options.all():
                existing = MCPConfigOption.objects.filter(mcp_id=keep_mcp.id, name=config_option.name).first()
                if not existing:
                    config_option.mcp_id = keep_mcp.id
                    config_option.save()
                else:
                    config_option.delete()
            
            for credential_template in mcp_to_remove.credential_templates.all():
                existing = MCPCredentialTemplate.objects.filter(mcp_id=keep_mcp.id, name=credential_template.name).first()
                if not existing:
                    credential_template.mcp_id = keep_mcp.id
                    credential_template.save()
                else:
                    credential_template.delete()
            
            mcp_to_remove.delete()
    
    for mcp in MCP.objects.all():
        if mcp.agent_id:
            agent = Agent.objects.get(pk=mcp.agent_id)
            agent.mcps.add(mcp)


def reverse_migrate(apps, schema_editor):
    """Reverte a migração: não é possível reverter automaticamente."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0022_make_agentsystem_metadata_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mcps',
            field=models.ManyToManyField(blank=True, related_name='agents', to='inline_agents.mcp'),
        ),
        migrations.RunPython(
            consolidate_duplicate_mcps_and_migrate_relationships,
            reverse_migrate,
        ),
        migrations.AlterUniqueTogether(
            name='mcp',
            unique_together={('system', 'name')},
        ),
        migrations.RemoveField(
            model_name='mcp',
            name='agent',
        ),
    ]
