# Generated by Django 5.1.5 on 2025-01-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0026_agentsystem_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroupModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_example', models.JSONField(blank=True, default=list)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modal', to='inline_agents.agentgroup')),
            ],
        ),
    ]
