# Generated by Django 4.2.27 on 2026-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0023_remove_agent_unused_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageragent',
            name='append_manager_extra_args',
            field=models.BooleanField(default=True, help_text='If True, the manager extra args will be appended to the collaborator extra args'),
        ),
        migrations.AddField(
            model_name='manageragent',
            name='collaborator_extra_args',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='manageragent',
            name='manager_extra_args',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
