# Generated by Django manually

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0023_alter_mcp_unique_together_agent_mcps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsystem',
            name='logo',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='agent_systems/logos/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])],
            ),
        ),
    ]
