# Generated by Django 5.1.5 on 2025-01-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inline_agents", "0023_remove_agent_unused_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="constants",
        ),
    ]
