# Generated by Django 4.2.27 on 2026-01-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0023_alter_mcp_unique_together_agent_mcps_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupervisorAgent',
        ),
    ]
