# Generated by Django 4.2.27 on 2026-01-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0023_supervisoragent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupervisorAgent',
        ),
    ]
