# Generated by Django 4.2.27 on 2026-02-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0024_alter_agentsystem_logo'),
        ('inline_agents', '0024_manageragent_append_manager_extra_args_and_more'),
    ]

    operations = [
    ]
