# Generated by Django 4.2.27 on 2026-01-20 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0024_delete_supervisoragent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('default', models.BooleanField(default=False, help_text='If True, this is the default supervisor for all newly created projects')),
                ('public', models.BooleanField(default=True, help_text='If True, this supervisor is public and will be available to all projects')),
                ('release_date', models.DateTimeField(help_text='The date and time when this supervisor will be set in older projects')),
                ('name', models.CharField(max_length=255)),
                ('base_prompt', models.TextField(blank=True, null=True)),
                ('foundation_model', models.CharField(max_length=255)),
                ('model_vendor', models.CharField(max_length=255)),
                ('model_has_reasoning', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_base', models.CharField(blank=True, max_length=255, null=True)),
                ('api_version', models.CharField(blank=True, max_length=255, null=True)),
                ('max_tokens', models.PositiveIntegerField(default=2048)),
                ('collaborator_max_tokens', models.PositiveIntegerField(default=2048)),
                ('reasoning_effort', models.CharField(blank=True, max_length=50, null=True)),
                ('reasoning_summary', models.CharField(blank=True, default='auto', max_length=50, null=True)),
                ('parallel_tool_calls', models.BooleanField(default=False)),
                ('tools', models.JSONField(blank=True, null=True)),
                ('knowledge_bases', models.JSONField(blank=True, null=True)),
                ('human_support_prompt', models.TextField(blank=True, null=True)),
                ('human_support_tools', models.JSONField(blank=True, null=True)),
                ('audio_orchestration_max_tokens', models.PositiveIntegerField(default=2048)),
                ('audio_orchestration_collaborator_max_tokens', models.PositiveIntegerField(default=2048)),
                ('header_components_prompt', models.TextField(blank=True, null=True)),
                ('footer_components_prompt', models.TextField(blank=True, null=True)),
                ('component_tools_descriptions', models.JSONField(blank=True, default=dict, null=True)),
                ('formatter_agent_prompt', models.TextField(blank=True, null=True)),
                ('formatter_agent_reasoning_effort', models.CharField(blank=True, max_length=50, null=True)),
                ('formatter_agent_reasoning_summary', models.CharField(blank=True, default='auto', max_length=50, null=True)),
                ('formatter_agent_send_only_assistant_message', models.BooleanField(default=False)),
                ('formatter_agent_tools_descriptions', models.JSONField(blank=True, default=dict, null=True)),
                ('formatter_agent_foundation_model', models.CharField(max_length=255)),
                ('formatter_agent_model_has_reasoning', models.BooleanField(default=False)),
                ('formatter_tools_descriptions', models.JSONField(blank=True, default=dict, null=True)),
                ('collaborators_foundation_model', models.CharField(max_length=255)),
                ('override_collaborators_foundation_model', models.BooleanField(default=False)),
                ('default_instructions_for_collaborators', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
