# Generated by Django 4.2.29 on 2026-04-09 14:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_manager_agent'),
        ('inline_agents', '0027_manageragent_max_tokens_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=255)),
                ('model_vendor', models.CharField(max_length=255)),
                ('credentials', models.JSONField(default=dict)),
                ('models', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('credentials', models.JSONField(default=list)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_provider', to='projects.project')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inline_agents.modelprovider')),
            ],
        ),
    ]
