# Generated by Django 4.2.29 on 2026-04-14 23:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_project_inline_agent_switch_default'),
        ('inline_agents', '0028_mcp_and_modal_locale_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('label', models.CharField(max_length=255)),
                ('model_vendor', models.CharField(max_length=255, unique=True)),
                ('credentials', models.JSONField(default=list)),
                ('manager_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inline_agents.manageragent')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('credentials', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_providers', to='projects.project')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inline_agents.modelprovider')),
            ],
            options={
                'unique_together': {('project', 'provider')},
            },
        ),
    ]
