# Generated by Django 4.2.29 on 2026-04-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0030_seed_model_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='credentials',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='modelprovider',
            name='model_vendor',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
