# Generated by Django 4.2.6 on 2023-11-07 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0002_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intelligence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('content_bases_count', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligences', to='orgs.org')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegratedIntelligence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('intelligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligences.intelligence')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentBase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('intelligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='intelligences.intelligence')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentBaseText',
            fields=[
                ('contentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intelligences.contentbase')),
                ('text', models.TextField()),
                ('content_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentbasetexts', to='intelligences.contentbase')),
            ],
            options={
                'abstract': False,
            },
            bases=('intelligences.contentbase',),
        ),
        migrations.CreateModel(
            name='ContentBaseLink',
            fields=[
                ('contentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intelligences.contentbase')),
                ('link', models.URLField()),
                ('content_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentbaselinks', to='intelligences.contentbase')),
            ],
            options={
                'abstract': False,
            },
            bases=('intelligences.contentbase',),
        ),
        migrations.CreateModel(
            name='ContentBaseFile',
            fields=[
                ('contentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intelligences.contentbase')),
                ('file', models.URLField()),
                ('extension_file', models.CharField(max_length=10)),
                ('content_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentbasefiles', to='intelligences.contentbase')),
            ],
            options={
                'abstract': False,
            },
            bases=('intelligences.contentbase',),
        ),
    ]
