# Generated by Django 4.2.8 on 2024-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbasefile',
            name='file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
