# Generated by Django 4.2.8 on 2024-01-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0003_contentbasetext_file_contentbasetext_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentbase",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
