# Generated by Django 4.2.8 on 2024-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0003_contentbasetext_file_contentbasetext_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentbasefile",
            name="file",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentbasefile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
