# Generated by Django 4.2.8 on 2024-01-24 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0004_alter_contentbasefile_file_and_more"),
        ("intelligences", "0004_contentbase_description"),
    ]

    operations = []
