# Generated by Django 4.2.8 on 2024-01-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0006_alter_contentbasetext_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbase',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish')], default='pt-br', max_length=10),
        ),
    ]
