# Generated by Django 4.2.8 on 2024-02-01 02:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0007_contentbase_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentbase",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contentbasefile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contentbaselink",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="contentbasetext",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="integratedintelligence",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="intelligence",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
