# Generated by Django 4.2.8 on 2024-02-15 20:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0008_alter_contentbase_uuid_alter_contentbasefile_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBaseLogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                ("language", models.CharField(max_length=10)),
                ("texts_chunks", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ("full_prompt", models.TextField()),
                ("weni_gpt_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("wenigpt_version", models.CharField(default="1.0.0", max_length=255)),
                (
                    "content_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="intelligences.contentbase",
                    ),
                ),
            ],
        ),
    ]
