# Generated by Django 4.2.10 on 2024-03-05 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0009_contentbaselogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbaselogs',
            name='correct_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentbaselogs',
            name='testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentbaselogs',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[(0, 'Resposta foi em um assunto completamente diferente do perguntado.'), (1, 'Resposta foi parcialmente correta, pois além da parte correta, trouxe informações no mesmo tema mas fora do contexto disponível.'), (2, 'Resposta foi parcialmente correta, pois além da parte correta, trouxe informações de um tema completamente diferente.'), (3, 'Respondeu que não possui a informação para fornecer a resposta, porém a informação consta no contexto disponível.')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('content_base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to='intelligences.contentbaselogs')),
            ],
        ),
    ]
