# Generated by Django 4.2.10 on 2024-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0010_contentbaselogs_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbaselogs',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('0', 'Resposta foi em um assunto completamente diferente do perguntado.'), ('1', 'Resposta foi parcialmente correta, pois além da parte correta, trouxe informações no mesmo tema mas fora do contexto disponível.'), ('2', 'Resposta foi parcialmente correta, pois além da parte correta, trouxe informações de um tema completamente diferente.'), ('3', 'Respondeu que não possui a informação para fornecer a resposta, porém a informação consta no contexto disponível.')], max_length=100, null=True),
        ),
    ]
