# Generated by Django 4.2.10 on 2024-03-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0010_alter_contentbaselogs_wenigpt_version'),
        ('intelligences', '0010_contentbaselogs_correct_answer_and_more'),
    ]

    operations = [
    ]
