# Generated by Django 4.2.10 on 2024-04-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0011_contentbase_is_router'),
        ('intelligences', '0011_merge_20240328_1856'),
    ]

    operations = [
    ]
