# Generated by Django 4.2.10 on 2024-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0012_merge_20240402_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentbaselogs",
            name="wenigpt_version",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
