# Generated by Django 4.2.10 on 2024-04-02 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intelligences', '0013_alter_contentbaselogs_wenigpt_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('top_p', models.FloatField()),
                ('top_k', models.FloatField()),
                ('threshold', models.FloatField()),
                ('max_length', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('intelligence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intelligences.integratedintelligence')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
