# Generated by Django 4.2.10 on 2024-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0015_contentbaseinstruction_contentbaseagent"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentbaselink",
            name="name",
            field=models.CharField(
                help_text="used to manage file with content from the link in bedrock", max_length=255, null=True
            ),
        ),
    ]
