# Generated by Django 4.2.10 on 2025-03-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0016_contentbaselink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbase',
            name='_indexer_database',
            field=models.CharField(blank=True, choices=[('SENTENX', 'Sentenx'), ('BEDROCK', 'Bedrock')], max_length=15, null=True),
        ),
    ]
