# Generated by Django 4.2.10 on 2025-07-04 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0005_alter_agentcredential_unique_together'),
        ('projects', '0014_project_default_supervisor_foundation_model'),
        ('intelligences', '0017_topics_subtopics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csat', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='inline_agents.inlineagentmessage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='intelligences.topics')),
            ],
        ),
    ]
