# Generated by Django 4.2.10 on 2025-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0018_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtopics",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topics",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
