# Generated by Django 4.2.10 on 2025-07-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inline_agents', '0005_alter_agentcredential_unique_together'),
        ('intelligences', '0018_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact_urn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='has_chats_room',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='intelligences.conversation')),
                ('message', models.ManyToManyField(related_name='conversations', to='inline_agents.inlineagentmessage')),
            ],
        ),
    ]
