# Generated by Django 4.2.10 on 2025-07-17 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0020_remove_conversation_message_conversation_contact_urn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="intelligences.topics",
            ),
        ),
    ]
