# Generated by Django 4.2.10 on 2025-08-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0021_alter_conversation_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="nps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="resolution",
            field=models.CharField(
                choices=[(0, "Resolved"), (1, "Unresolved"), (2, "In Progress")], default=2, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="subtopic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="intelligences.subtopics",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="csat",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "Very unsatisfied"),
                    (2, "Unatisfied"),
                    (3, "Neutral"),
                    (4, "Satisfied"),
                    (5, "Very satisfied"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
