# Generated by Django 4.2.10 on 2025-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0022_conversation_nps_conversation_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
