# Generated by Django 4.2.10 on 2025-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0023_conversation_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='resolution',
            field=models.CharField(choices=[(0, 'Resolved'), (1, 'Unresolved')], default=0, max_length=255),
        ),
    ]
