# Generated by Django 4.2.10 on 2025-09-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intelligences", "0025_alter_conversation_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="intelligence",
            name="is_router",
            field=models.BooleanField(default=False),
        ),
    ]
