# Generated by Django 4.2.10 on 2025-10-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0026_intelligence_is_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='resolution',
            field=models.CharField(choices=[(0, 'Resolved'), (1, 'Unresolved'), (2, 'In Progress'), (3, 'Unclassified'), (4, 'Has Chat Room')], default=2, max_length=255),
        ),
    ]
