# Generated by Django 4.2.10 on 2025-07-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0026_alter_conversation_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='resolution',
            field=models.CharField(choices=[(0, 'Resolved'), (1, 'Unresolved'), (2, 'In Progress')], default=2, max_length=255),
        ),
    ]
