# Generated by Django 4.2.10 on 2025-08-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0027_alter_conversation_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='csat',
            field=models.CharField(blank=True, choices=[(1, 'Very unsatisfied'), (2, 'Unatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very satisfied')], max_length=255, null=True),
        ),
    ]
