# Generated by Django 4.2.10 on 2025-10-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0027_alter_conversation_resolution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
