# Generated by Django 4.2.27 on 2026-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligences', '0029_contentbasetext_title_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbasetext',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
