# Generated by Django 4.2.6 on 2023-11-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('softdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='db.softdeletemodel')),
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.basemodel')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('db.basemodel', 'db.softdeletemodel'),
        ),
    ]
