# Generated by Django 4.2.8 on 2024-02-01 02:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0003_orgauth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
