# Generated by Django 4.2.8 on 2024-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_org_inteligence_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='inteligence_organization',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
