# Generated by Django 4.2.10 on 2024-04-18 18:16

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("intelligences", "0015_contentbaseinstruction_contentbaseagent"),
        ("projects", "0004_project_brain_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("contact_urn", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("F", "fail"), ("P", "processing"), ("S", "success")], default="P", max_length=1
                    ),
                ),
                ("exception", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "chunks",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
                ),
                ("prompt", models.TextField()),
                ("classification", models.CharField(max_length=255, null=True)),
                ("llm_model", models.CharField(max_length=255, null=True)),
                ("llm_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(null=True)),
                (
                    "content_base",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="intelligences.contentbase"
                    ),
                ),
                ("message", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="logs.message")),
                (
                    "project",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
                ),
            ],
        ),
    ]
