# Generated by Django 4.2.10 on 2024-05-28 13:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_projectauth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intelligences", "0015_contentbaseinstruction_contentbaseagent"),
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentActivities",
            fields=[
                ("action_model", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("action_details", models.JSONField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(choices=[("C", "created"), ("U", "updated"), ("D", "deleted")], max_length=1),
                ),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "intelligence",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="intelligences.intelligence"),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project")),
            ],
        ),
    ]
