# Generated by Django 4.2.10 on 2024-10-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_recentactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
