# Generated by Django 4.2.10 on 2024-10-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_messagelog_groundedness_score_and_more'),
        ('logs', '0003_messagelog_source'),
    ]

    operations = [
    ]
