# Generated by Django 4.2.10 on 2024-11-07 18:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_messagelog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='chunks_json',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None),
        ),
    ]
