# Generated by Django 4.2.10 on 2024-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_messagelog_chunks_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
