# Generated by Django 4.2.10 on 2024-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_messagelog_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='groundedness_details',
            field=models.JSONField(null=True),
        ),
    ]
